import { StyleSheet } from 'react-native';
import { colors, fonts } from '../../styles/BaseStyles';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.backgroundLight,
    },
    scrollContainer: {
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 40,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    userInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    userTextContainer: {
        marginLeft: 10,
    },
    welcomeSubtitle: {
        fontSize: 14,
        color: colors.textMuted,
        fontFamily: fonts.Regular,
    },
    locationText: {
        fontSize: 12,
        color: colors.textDark,
        fontFamily: fonts.Medium,
        marginTop: 2,
    },
    avatarThumbnail: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        backgroundColor: colors.gray,
    },
    notificationButton: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.borderLight,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    bellIcon: {
        width: 20,
        height: 20,
        resizeMode: 'contain',
    },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    searchBarContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 14,
        paddingHorizontal: 14,
        height: 50,
        borderWidth: 1,
        borderColor: colors.borderLight,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 3,
    },
    searchInput: {
        flex: 1,
        fontFamily: fonts.Regular,
        color: colors.textDark,
        fontSize: 14,
        paddingVertical: 0,
    },
    filterButton: {
        width: 50,
        height: 50,
        borderRadius: 14,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
        borderWidth: 1,
        borderColor: colors.borderLight,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 3,
    },
    promoBanner: {
        height: 160,
        marginBottom: 24,
        borderRadius: 20,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
    },
    promoImageStyle: {
        borderRadius: 20,
    },
    promoOverlay: {
        flex: 1,
        backgroundColor: colors.overlay,
        padding: 20,
        justifyContent: 'center',
    },
    promoContent: {
        width: '80%',
    },
    promoTitle: {
        fontSize: 18,
        fontFamily: fonts.Bold,
        color: colors.white,
        marginBottom: 6,
    },
    promoSubtitle: {
        fontSize: 12,
        fontFamily: fonts.Regular,
        color: colors.white,
        marginBottom: 14,
        lineHeight: 18,
    },
    promoButton: {
        backgroundColor: colors.white,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        alignSelf: 'flex-start',
    },
    promoButtonText: {
        color: colors.orangeDark,
        fontFamily: fonts.Bold,
        fontSize: 13,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 18,
        color: colors.textDark,
        fontFamily: fonts.Bold,
        letterSpacing: -0.2,
    },
    viewAllButton: {
        fontSize: 13,
        color: colors.blue,
        fontFamily: fonts.SemiBold,
    },
    categoryCard: {
        alignItems: 'center',
        marginRight: 14,
        backgroundColor: colors.white,
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.borderLight,
        minWidth: 80,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 2,
    },
    categoryCardSelected: {
        backgroundColor: colors.blue,
        borderColor: colors.blue,
    },
    categoryIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: colors.backgroundLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    categoryIconWrapperSelected: {
        backgroundColor: colors.inputBg,
    },
    categoryText: {
        fontSize: 12,
        color: colors.textMuted,
        fontFamily: fonts.Medium,
    },
    categoryTextSelected: {
        color: colors.white,
        fontFamily: fonts.Bold,
    },
    galleryContainer: {
        paddingBottom: 10,
    },
    galleryCard: {
        width: 175,
        backgroundColor: colors.white,
        borderRadius: 16,
        marginRight: 14,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.borderLight,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
    },
    imageContainer: {
        position: 'relative',
    },
    cardImage: {
        width: '100%',
        height: 120,
        backgroundColor: colors.gray,
    },
    ratingBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: colors.errorBg,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    cardRating: {
        fontSize: 11,
        color: colors.white,
        fontFamily: fonts.Bold,
    },
    cardInfo: {
        padding: 12,
    },
    cardTitle: {
        fontSize: 14,
        color: colors.textDark,
        fontFamily: fonts.Bold,
        marginBottom: 4,
    },
    cardDescription: {
        fontSize: 11,
        color: colors.textMuted,
        fontFamily: fonts.Regular,
        lineHeight: 15,
    },
    emptyText: {
        color: colors.textMuted,
        fontFamily: fonts.Regular,
        textAlign: 'center',
        marginTop: 10,
        fontSize: 13,
    },
});

export default styles;